//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class UniversalcarsaletestcaseTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void universalcarsaletestcase() {
//    // Test name: Universal car sale test case
//    // Step # | name | target | value
//    // 1 | open | /UnicersalCarSalePortal/login.html |
//    driver.get("http://localhost:63342/UnicersalCarSalePortal/login.html");
//    // 2 | setWindowSize | 1382x744 |
//    driver.manage().window().setSize(new Dimension(1382, 744));
//    // 3 | click | linkText=Sign Up |
//    driver.findElement(By.linkText("Sign Up")).click();
//    // 4 | click | id=fullName-field |
//    driver.findElement(By.id("fullName-field")).click();
//    // 5 | type | id=fullName-field | Shamain Nawoda
//    driver.findElement(By.id("fullName-field")).sendKeys("Shamain Nawoda");
//    // 6 | click | id=address-field |
//    driver.findElement(By.id("address-field")).click();
//    // 7 | type | id=address-field | Aluthgama
//    driver.findElement(By.id("address-field")).sendKeys("Aluthgama");
//    // 8 | click | id=email-field |
//    driver.findElement(By.id("email-field")).click();
//    // 9 | type | id=email-field | shamain@gmail.com
//    driver.findElement(By.id("email-field")).sendKeys("shamain@gmail.com");
//    // 10 | click | id=contact-field |
//    driver.findElement(By.id("contact-field")).click();
//    // 11 | type | id=contact-field | 07755886062
//    driver.findElement(By.id("contact-field")).sendKeys("07755886062");
//    // 12 | click | id=nic-field |
//    driver.findElement(By.id("nic-field")).click();
//    // 13 | type | id=nic-field | 147852369v
//    driver.findElement(By.id("nic-field")).sendKeys("147852369v");
//    // 14 | click | css=#addCustomer > .px-2 |
//    driver.findElement(By.cssSelector("#addCustomer > .px-2")).click();
//    // 15 | click | id=fullName-field |
//    driver.findElement(By.id("fullName-field")).click();
//    // 16 | type | id=fullName-field | 147852369v
//    driver.findElement(By.id("fullName-field")).sendKeys("147852369v");
//    // 17 | click | id=password-field |
//    driver.findElement(By.id("password-field")).click();
//    // 18 | type | id=password-field | 1234
//    driver.findElement(By.id("password-field")).sendKeys("1234");
//    // 19 | click | id=signUp |
//    driver.findElement(By.id("signUp")).click();
//    // 20 | click | css=.btn-outline-success |
//    driver.findElement(By.cssSelector(".btn-outline-success")).click();
//    // 21 | click | linkText=Home |
//    driver.findElement(By.linkText("Home")).click();
//    // 22 | click | id=supply |
//    driver.findElement(By.id("supply")).click();
//    // 23 | click | id=fullName-field |
//    driver.findElement(By.id("fullName-field")).click();
//    // 24 | type | id=fullName-field | New Supplier
//    driver.findElement(By.id("fullName-field")).sendKeys("New Supplier");
//    // 25 | click | id=address-field |
//    driver.findElement(By.id("address-field")).click();
//    // 26 | type | id=address-field | Colombo 02
//    driver.findElement(By.id("address-field")).sendKeys("Colombo 02");
//    // 27 | click | id=email-field |
//    driver.findElement(By.id("email-field")).click();
//    // 28 | type | id=email-field | sup@gmail.com
//    driver.findElement(By.id("email-field")).sendKeys("sup@gmail.com");
//    // 29 | click | id=contact-field |
//    driver.findElement(By.id("contact-field")).click();
//    // 30 | type | id=contact-field | 0789936062
//    driver.findElement(By.id("contact-field")).sendKeys("0789936062");
//    // 31 | click | id=nic-field |
//    driver.findElement(By.id("nic-field")).click();
//    // 32 | type | id=nic-field | 123789456v
//    driver.findElement(By.id("nic-field")).sendKeys("123789456v");
//    // 33 | click | css=.px-2 |
//    driver.findElement(By.cssSelector(".px-2")).click();
//    // 34 | click | id=fullName-field |
//    driver.findElement(By.id("fullName-field")).click();
//    // 35 | type | id=fullName-field | 123789456v
//    driver.findElement(By.id("fullName-field")).sendKeys("123789456v");
//    // 36 | click | id=password-field |
//    driver.findElement(By.id("password-field")).click();
//    // 37 | type | id=password-field | 1245
//    driver.findElement(By.id("password-field")).sendKeys("1245");
//    // 38 | click | id=signUp |
//    driver.findElement(By.id("signUp")).click();
//    // 39 | click | id=supplyOp |
//    driver.findElement(By.id("supplyOp")).click();
//    // 40 | click | id=nic |
//    driver.findElement(By.id("nic")).click();
//    // 41 | type | id=nic | 123789456v
//    driver.findElement(By.id("nic")).sendKeys("123789456v");
//    // 42 | click | id=search |
//    driver.findElement(By.id("search")).click();
//    // 43 | click | id=fullName |
//    driver.findElement(By.id("fullName")).click();
//    // 44 | click | id=phone |
//    driver.findElement(By.id("phone")).click();
//    // 45 | click | id=Address |
//    driver.findElement(By.id("Address")).click();
//    // 46 | mouseDownAt | css=.row:nth-child(1) > .col-xl-6:nth-child(2) | 398.111083984375,54.854156494140625
//    {
//      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(1) > .col-xl-6:nth-child(2)"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).clickAndHold().perform();
//    }
//    // 47 | mouseMoveAt | css=.row:nth-child(1) > .col-xl-6:nth-child(2) | 398.111083984375,54.854156494140625
//    {
//      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(1) > .col-xl-6:nth-child(2)"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    // 48 | mouseUpAt | css=.row:nth-child(1) > .col-xl-6:nth-child(2) | 398.111083984375,54.854156494140625
//    {
//      WebElement element = driver.findElement(By.cssSelector(".row:nth-child(1) > .col-xl-6:nth-child(2)"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).release().perform();
//    }
//    // 49 | click | css=.card-body > .row:nth-child(1) |
//    driver.findElement(By.cssSelector(".card-body > .row:nth-child(1)")).click();
//    // 50 | click | id=eMail |
//    driver.findElement(By.id("eMail")).click();
//    // 51 | click | id=eMail |
//    driver.findElement(By.id("eMail")).click();
//    // 52 | type | id=eMail | supplier@gmail.com
//    driver.findElement(By.id("eMail")).sendKeys("supplier@gmail.com");
//    // 53 | click | id=update |
//    driver.findElement(By.id("update")).click();
//    // 54 | click | linkText=Home |
//    driver.findElement(By.linkText("Home")).click();
//    // 55 | click | id=productURL |
//    driver.findElement(By.id("productURL")).click();
//    // 56 | click | css=.fa-solid |
//    driver.findElement(By.cssSelector(".fa-solid")).click();
//    // 57 | click | css=b > .btn:nth-child(2) |
//    driver.findElement(By.cssSelector("b > .btn:nth-child(2)")).click();
//    // 58 | click | css=b > .btn:nth-child(1) |
//    driver.findElement(By.cssSelector("b > .btn:nth-child(1)")).click();
//    // 59 | runScript | window.scrollTo(0,17) |
//    js.executeScript("window.scrollTo(0,17)");
//    // 60 | mouseOver | css=.gtm-market-logo |
//    {
//      WebElement element = driver.findElement(By.cssSelector(".gtm-market-logo"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    // 61 | click | css=.btn:nth-child(5) |
//    driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
//  }
//}
